version: '3.9'

services:
  nlu-api:
    container_name: nlu-api
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - nlu-network
    volumes:
      - nlu-data:/app/repos
    healthcheck:
      test: curl --fail http://localhost:5000/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - 5000:5000

volumes:
  nlu-data:

networks:
  nlu-network:
